# TCL File Generated by Component Editor 18.1
# Thu Feb 07 17:06:54 BRT 2019
# DO NOT MODIFY


# 
# my_register_slave_interface "my_register_slave_interface" v1.0
#  2019.02.07.17:06:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_register_slave_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME my_register_slave_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP emerson
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME my_register_slave_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL my_register_slave_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_register.v VERILOG PATH my_register.v
add_fileset_file my_register_slave_interface.v VERILOG PATH my_register_slave_interface.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset clock clk Input 1


# 
# connection point avalon_slave_0_1_1
# 
add_interface avalon_slave_0_1_1 avalon end
set_interface_property avalon_slave_0_1_1 addressUnits WORDS
set_interface_property avalon_slave_0_1_1 associatedClock clock_reset
set_interface_property avalon_slave_0_1_1 associatedReset reset_sink
set_interface_property avalon_slave_0_1_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1_1 holdTime 0
set_interface_property avalon_slave_0_1_1 isMemoryDevice true
set_interface_property avalon_slave_0_1_1 linewrapBursts false
set_interface_property avalon_slave_0_1_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1_1 readLatency 0
set_interface_property avalon_slave_0_1_1 readWaitTime 1
set_interface_property avalon_slave_0_1_1 setupTime 0
set_interface_property avalon_slave_0_1_1 timingUnits Cycles
set_interface_property avalon_slave_0_1_1 writeWaitTime 0
set_interface_property avalon_slave_0_1_1 ENABLED true
set_interface_property avalon_slave_0_1_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1_1 byte_enable byteenable Input 4
add_interface_port avalon_slave_0_1_1 writedata writedata Input 32
add_interface_port avalon_slave_0_1_1 readdata readdata Output 32
add_interface_port avalon_slave_0_1_1 read read Input 1
add_interface_port avalon_slave_0_1_1 write write Input 1
add_interface_port avalon_slave_0_1_1 chip_select chipselect Input 1
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end to_lights readdata Output 32


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_reset
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink resetn reset_n Input 1

